const $=s=>document.querySelector(s), app=$('#app');
const STORE='midnight_express_save_v1', CFG='midnight_express_config_v1', STATS='midnight_express_stats_v1';
const carriages=[
 {id:1,name:'商务座',desc:'柔和的灯光照着深红窗帘。咖啡早已冷透，三天前的报纸在风口轻轻颤动。',areas:['座位夹缝','报架','垃圾桶','行李架']},
 {id:2,name:'卧铺',desc:'上下铺的帘子半掩着，走廊狭窄。尽头的应急灯忽明忽暗。',areas:['枕头下','走廊角落','洗手间','铺位缝隙']},
 {id:3,name:'餐车 · 现场',desc:'坏掉的灯管嗡嗡作响。周明的座位被绳子围住，空气里混着一股刺鼻气味。',areas:['周明的座位','厨房区域','餐桌下面','垃圾桶','收银台抽屉']},
 {id:4,name:'行李车',desc:'行李将昏暗空间切成碎片。角落传来滴水声，一只蒙布的大箱子沉默地立着。',areas:['行李堆','角落阴影','滴水处','蒙布大箱','地板缝']}
];
const NPCS=[
 {id:'lin',name:'林教授',full:'林伯年',age:65,job:'退休教授',icon:'👓',car:1,style:'温和、引经据典',secret:'他因学术造假被大学开除，身份证和教授身份都是伪造的。',why:'害怕自己的假身份被揭穿。',base:.36},
 {id:'su',name:'苏小姐',full:'苏婉清',age:35,job:'珠宝商人',icon:'🧣',car:1,style:'优雅、冷淡、简洁',secret:'银色手提箱暗格里藏着一批走私翡翠。',why:'害怕走私生意曝光。',base:.28},
 {id:'chen',name:'老陈',full:'陈德水',age:50,job:'列车员',icon:'🧢',car:2,style:'热心、疲惫、爱操心',secret:'他欠下三十万元高利贷，追债人正威胁他的家人。',why:'不愿承认经济困境和案发时擅离岗位。',base:.52},
 {id:'jie',name:'阿杰',full:'杰哥',age:28,job:'背包客',icon:'🎒',car:2,style:'健谈、幽默、滑头',secret:'他是电信诈骗案嫌疑人，包里有三部手机、假证件和现金。',why:'他靠编造身份逃避追捕。',base:.32},
 {id:'wang',name:'王医生',full:'王启明',age:45,job:'外科医生',icon:'🩺',car:2,style:'冷静、寡言、精确',secret:'他两年前因手术失误致人死亡并篡改记录。',why:'即将到来的调查令他恐惧。',base:.38},
 {id:'yu',name:'小雨',full:'周小雨',age:21,job:'大学生',icon:'🎓',car:3,style:'紧张、迟疑、敏感',secret:'她是周明的亲妹妹，上车是为了寻找失联三天的哥哥。',why:'担心凶手知道她的身份后伤害她。',base:.22},
 {id:'zhao',name:'赵老板',full:'赵富贵',age:55,job:'煤矿老板',icon:'📿',car:3,style:'粗犷、洪亮、易怒',secret:'他曾花钱掩盖煤矿事故，并雇人阻止一名工人上告。',why:'他的暴力前科足以毁掉一切。',base:.3},
 {id:'mute',name:'哑叔',full:'姓名不详',age:'不详',job:'流浪汉',icon:'🧥',car:4,style:'沉默、用动作表达',secret:'他是患有创伤后应激障碍的退伍军人，案发时一直醒着。',why:'他已习惯没人认真听他说话。',base:.16}
];
const motives={
 lin:['周明认出了他的真实身份，并准备公开学术造假的全部证据。','假身份曝光'],
 su:['周明发现了银色箱子的暗格，威胁下车后立刻报警。','走私秘密'],
 chen:['周明正是追债人的代理，威胁要对他的女儿下手。','绝境债务'],
 jie:['周明认出了诈骗案通缉照片上的他，还偷偷拍下证据。','逃避追捕'],
 wang:['周明是医疗事故死者的家属，带着原始病历来找他对质。','医疗事故'],
 zhao:['周明掌握了矿难封口协议，准备把它交给调查记者。','掩盖矿难'],
 mute:['周明无意中触发了他的战场创伤，他在应激失控中造成了意外。','创伤失控']
};
const culpritClues={
 lin:[['被撕碎的合影','照片背面写着“伯年，论文不能这样写”。碎片上的年轻人正是周明。',3],['旧校徽纽扣','一枚停产多年的大学校徽纽扣，卡在餐桌下面。',3],['伪造证件边角','商务座垃圾桶里有被撕下的覆膜，与林教授证件吻合。',1],['墨水指纹','行李车箱盖上的蓝黑墨水指纹，林教授钢笔使用同款墨水。',4],['被圈出的报道','旧报纸上“学术诚信追责”一文被重重圈出。',1]],
 su:[['翡翠碎屑','周明座位下有一小片未经加工的翡翠，边缘新鲜断裂。',3],['银色搭扣','餐车垃圾桶里有手提箱暗格的微型搭扣。',3],['化学清洗剂','商务座行李架上残留珠宝清洗剂，气味与现场一致。',1],['染红丝巾','行李车暗处藏着一条丝巾，红色并不是血而是染料。',4],['交易便笺','报纸夹层写着“货在银箱，周明验”。',1]],
 chen:[['万能钥匙印痕','餐车收银台锁上有新鲜划痕，来自列车员的万能钥匙。',3],['催债短信','卧铺角落有一张短信打印件：“周一之前还不上，你知道后果。”',2],['制服纽扣','周明座位夹缝中卡着一枚旧铁路制服纽扣。',3],['现金封带','行李车地板缝里有银行现金封带，上面留着老陈的汗渍。',4],['值班表涂改','列车员值班表的00:00一栏被人改过。',2]],
 jie:[['模糊偷拍照','周明手机云端打印照片里，阿杰的侧脸被红笔圈出。',3],['第三部手机卡','洗手间水箱后藏着一张未实名电话卡。',2],['运动鞋泥印','餐车厨房门口的鞋印与阿杰鞋底缺口完全吻合。',3],['假证件碎片','行李车滴水处漂着半张被泡烂的假身份证。',4],['现金捆扎带','卧铺缝隙里有诈骗团伙常用的蓝色捆扎带。',2]],
 wang:[['镇静剂空瓶','餐车垃圾桶中有一只无标签药瓶，残留强效镇静成分。',3],['乳胶手套碎片','周明桌下有一片医用手套，撕裂方向指向左手。',3],['旧病历页','卧铺枕下压着一页被涂改的手术记录。',2],['冷藏袋','行李车蒙布箱后藏着一个医院用冷藏袋。',4],['处方字迹','收银台便笺上的字迹与王医生处方签一致。',3]],
 zhao:[['矿难协议碎片','撕碎照片背后其实粘着一角封口协议，有赵富贵的签名。',3],['金链扣环','周明座位旁发现一枚粗金链扣，断口很新。',3],['煤灰脚印','厨房后门有煤灰鞋印，鞋码与赵老板一致。',3],['染料手帕','行李堆深处有沾红色标记染料的手帕，并不是血。',4],['威胁录音卡','收银台抽屉里藏着存储卡，录有赵老板威胁周明。',3]],
 mute:[['旧军章','餐桌下有一枚磨损军章，背面刻着编号。',3],['拖拽布条','行李车地板缝夹着军大衣同材质的布条。',4],['药物说明书','行李堆里有治疗创伤应激的药物说明书。',4],['破碎水杯','餐车厨房发现带有哑叔指纹的碎玻璃。',3],['面包包装','周明座位旁有半块面包，包装上留下两个人的指纹。',3]]
};
const redHerrings=[
 ['银箱暗格','箱中是走私翡翠。危险的秘密，但和周明失踪未必有关。','su',1],
 ['三部旧手机','阿杰的背包里藏着三部手机和成叠现金。','jie',2],
 ['涂改病历','一份被篡改的手术记录，王医生明显不愿解释。','wang',2],
 ['高利贷短信','催债信息提到了老陈的女儿，语气充满威胁。','chen',2],
 ['矿难封口协议','协议记录了三年前被压下的事故。','zhao',4],
 ['假身份证','证件上的林伯年与眼前的人履历对不上。','lin',1]
];
const atmosphere=['车轮碾过铁轨，像一颗巨大的心脏在跳动。','窗外闪过一盏孤零零的信号灯，随后又归于黑暗。','灯光似乎比刚才暗了一些，没人提起这件事。','雨更大了，水痕把每个人的倒影割得支离破碎。','列车短暂减速。所有人都抬起头，却没有看到站台。','走廊尽头的应急灯不知何时熄灭了。','广播里传来无法辨认的杂音，像有人隔着很远说话。','空气沉重。每个人脸上都写着疲惫与不安。','远处传来汽笛。终点站……真的存在吗？','钟的秒针停了一瞬，又突然追赶起来。'];
let S=null,C=Object.assign({sound:true,speed:'normal',apiBase:'',apiKey:'',model:''},load(CFG)||{}),typingTimer=null;
function load(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}function save(){if(S)localStorage.setItem(STORE,JSON.stringify(S))}function cfgSave(){localStorage.setItem(CFG,JSON.stringify(C))}function npc(id){return NPCS.find(n=>n.id===id)}function state(id){return S.npcs[id]}function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}function chance(p){return Math.random()<p}function clamp(x){return Math.max(0,Math.min(1,x))}function pick(a){return a[Math.floor(Math.random()*a.length)]}
function initCase(identity){let pool=['lin','su','chen','jie','wang','zhao','mute'],culprit=pick(pool.concat(pool.filter(x=>x!=='mute'))),m=motives[culprit][0];let key=culpritClues[culprit].map((c,i)=>({id:'k'+i,name:c[0],desc:c[1],car:c[2],key:true,found:false,areaIndex:i%carriages[c[2]-1].areas.length}));let reds=[...redHerrings].filter(x=>x[2]!==culprit).sort(()=>Math.random()-.5).slice(0,3).map((c,i)=>({id:'r'+i,name:c[0],desc:c[1],owner:c[2],car:c[3],key:false,found:false,areaIndex:(i+1)%carriages[c[3]-1].areas.length}));let npcs={};NPCS.forEach(n=>npcs[n.id]={car:n.car,trust:clamp(n.base+(identity==='journalist'?.1:0)),stress:culprit===n.id?.42:.16+Math.random()*.16,suspicion:identity==='journalist'&&culprit===n.id?.25:.1,interactions:0,revealed:false,asked:[],alive:true});
 S={version:1,active:true,screen:'story',identity,round:1,currentCar:3,culprit,motive:m,clues:[...key,...reds],collected:[],notes:[],events:[],npcs,selected:null,scene:{speaker:'案发现场',text:'凌晨 1:13。尖叫声把所有人带到餐车。周明消失了，只剩暗红液体、碎照片和化学药品的气味。',obs:'没有人看见他离开。列车从未停靠。'},searched:{},muteTalks:0,lies:0,ended:false,created:Date.now()};if(identity==='friend'){let c=key[0];c.found=true;S.collected.push(c.id);S.notes.push({round:0,text:'你记得周明上车前曾提到：'+c.name+'。'})}save();}
function landing(){S=load(STORE);app.innerHTML=`<section class="screen landing"><span class="corner tl">K1024 / NORTH—SOUTH</span><div class="hero"><div class="eyebrow">一场每次都不同的谋杀谜局</div><div class="train-mark">🚂</div><h1 class="title">午夜列车</h1><div class="subtitle">MIDNIGHT EXPRESS</div><div class="rule"></div><p class="tagline">一列永不停靠的火车。<br>一个消失的乘客。八个各怀秘密的灵魂。</p><div class="landing-actions"><button class="btn primary big" onclick="identityPage()">开始调查</button><button class="btn" onclick="rules()">调查规则</button><button class="btn" onclick="settings()">设置</button></div>${S?.active&&!S.ended?'<button class="resume" onclick="resumeGame()">继续未完成的调查 →</button>':''}</div><span class="corner br">01:13 / SIGNAL LOST</span></section>`}
function identityPage(){app.innerHTML=`<section class="screen page"><div class="page-head"><div><div class="eyebrow">建立调查者档案</div><h1>你是谁？</h1><p>身份会改变他人看待你的方式。</p></div><button class="btn ghost" onclick="landing()">返回</button></div><div class="identity-grid">${[['journalist','📰','记者','人们更愿意回答，但凶手更警惕你。','初始信任 +10%'],['police','🔍','便衣警察','可以搜查嫌疑人的随身物品，但所有人更拘谨。','解锁随身搜查'],['passenger','🧳','普通乘客','最不起眼，因此也最容易让人放松。','关系变化更自然'],['friend','💔','周明的朋友','你带着一条私人线索上车，情感却可能干扰判断。','开局获得 1 条线索']].map((x,i)=>`<button class="identity" onclick="startGame('${x[0]}')"><span class="num">0${i+1}</span><span class="icon">${x[1]}</span><h3>${x[2]}</h3><p>${x[3]}</p><span class="perk">◆ ${x[4]}</span></button>`).join('')}</div></section>`}
function startGame(id){localStorage.removeItem(STORE);initCase(id);app.innerHTML=`<div class="loading"><div><div class="eyebrow">正在重组案发之夜</div><h2 style="font-family:var(--serif);letter-spacing:.15em">列车驶入隧道</h2><div class="loader"></div><p style="color:var(--muted);font-size:12px">凶手、动机与证据正在生成……</p></div></div>`;setTimeout(story,1200)}
function story(){S.screen='story';save();let txt='窗外是无边的黑暗。\n\n你在暴雨之夜登上 K1024 次列车。凌晨 1:13，餐车传来一声尖叫。\n\n乘客周明失踪了。座位上只留下暗红液体、被撕碎的照片，以及一股淡淡的化学气味。\n\n列车没有停过。你只有十个回合。';app.innerHTML=`<section class="screen narrative"><div class="story-card"><div class="story-time">01:13 AM · K1024</div><div id="storyText" class="story-text cursor"></div><button id="storyNext" class="btn primary" style="opacity:0" onclick="enterGame()">走进餐车</button></div></section>`;typeText($('#storyText'),txt,()=>{$('#storyText').classList.remove('cursor');$('#storyNext').style.opacity=1})}
function typeText(el,text,done){clearInterval(typingTimer);let i=0,speed=C.speed==='instant'?0:C.speed==='fast'?10:C.speed==='slow'?38:20;if(!speed){el.textContent=text;done&&done();return}typingTimer=setInterval(()=>{el.textContent=text.slice(0,++i);if(i>=text.length){clearInterval(typingTimer);done&&done()}},speed)}
function resumeGame(){S=load(STORE);if(!S)return landing();S.ended?resultPage(S.accused):S.screen==='story'?story():enterGame()}
function enterGame(){S.screen='game';save();renderGame()}
function emotion(ns){if(ns.stress>.85)return'😱';if(ns.stress>.7)return'😨';if(ns.suspicion>.55)return'🤨';if(ns.stress>.38)return'😰';if(ns.trust>.63)return'😊';return'😐'}
function renderGame(){if(!S)return landing();let here=NPCS.filter(n=>state(n.id).car===S.currentCar),scene=S.scene||{};app.innerHTML=`<section class="game"><header class="topbar"><div class="brand">🚂 午夜列车</div><div class="round">ROUND ${String(S.round).padStart(2,'0')} / 10</div><div><button class="icon-btn" title="规则" onclick="rules(true)">?</button><button class="icon-btn" title="设置" onclick="settings(true)">⚙</button></div></header><div class="game-body"><section class="panel map-panel"><div class="section-label">列车地图 · 点击移动</div><div class="carriages">${carriages.map(c=>{let ns=NPCS.filter(n=>state(n.id).car===c.id);return`<button class="carriage ${S.currentCar===c.id?'active':''}" onclick="moveTo(${c.id})"><span class="car-no">CAR 0${c.id}</span>${S.currentCar===c.id?'<span class="you">你在这里</span>':''}<strong>${c.name}</strong><span class="dots">${ns.map(()=>'<i class="npc-dot"></i>').join('')}</span></button>`}).join('')}</div></section><div class="workspace"><aside class="panel npc-panel"><div class="section-label">当前车厢 · ${here.length} 人</div><div class="npc-list">${here.map(n=>`<div class="npc-card ${S.selected===n.id?'selected':''}" onclick="selectNpc('${n.id}')"><div class="avatar">${n.icon}</div><div><div class="npc-name">${emotion(state(n.id))} ${n.name}</div><div class="npc-job">${n.job}</div><div class="meter"><i style="width:${state(n.id).stress*100}%"></i></div></div></div>`).join('')||'<div class="empty-note">这节车厢空无一人。<br>只有列车前行的声音。</div>'}</div></aside><section class="panel scene"><div class="scene-head"><span class="section-label" style="margin:0">${carriages[S.currentCar-1].name}</span><span style="font-size:10px;color:var(--muted)">${here.map(n=>n.name).join(' · ')||'无人'}</span></div><div class="scene-copy"><div class="speaker">${esc(scene.speaker||'环境')}</div><div id="dialogue" class="dialogue">${esc(scene.text||carriages[S.currentCar-1].desc)}</div>${scene.obs?`<div class="observation">◆ ${esc(scene.obs)}</div>`:''}</div><div class="actions"><button class="action" onclick="askModal()" ${!S.selected?'disabled':''}>询问</button><button class="action" onclick="eavesdrop()" ${here.length<2?'disabled':''}>偷听</button><button class="action" onclick="searchModal()">搜查</button><button class="action" onclick="evidenceModal()" ${!S.selected||!S.collected.length?'disabled':''}>出示证据</button><button class="action" onclick="follow()" ${!S.selected?'disabled':''}>跟踪</button><button class="action accuse" onclick="accuseModal()">⚠ 指认</button></div></section><aside class="panel intel-panel"><div class="tabs"><button class="tab active" onclick="showTab('clues',this)">线索 ${S.collected.length}/8</button><button class="tab" onclick="showTab('notes',this)">笔记 ${S.notes.length}</button></div><div id="intel" class="tab-content">${cluesHTML()}</div></aside></div><div class="panel ticker">${esc(S.events.at(-1)||atmosphere[Math.min(S.round-1,9)])}</div></div></section>`}
function cluesHTML(){let cs=S.collected.map(id=>S.clues.find(c=>c.id===id));return cs.length?cs.map(c=>`<div class="clue" onclick="clueDetail('${c.id}')"><b>${c.key?'🔸':'🔹'} ${esc(c.name)}</b><p>${esc(c.desc)}</p></div>`).join(''):'<div class="empty-note">线索板还是空的。<br>搜查车厢，或让某个人开口。</div>'}
function showTab(t,b){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#intel').innerHTML=t==='clues'?cluesHTML():S.notes.slice().reverse().map(n=>`<div class="note"><span>[回合 ${n.round}]</span> ${esc(n.text)}</div>`).join('')||'<div class="empty-note">还没有调查记录。</div>'}
function selectNpc(id){S.selected=id;let n=npc(id),ns=state(id);S.scene={speaker:n.name,text:profileLine(n,ns),obs:`${n.full}，${n.age}岁，${n.job}。目前看起来${ns.stress>.5?'非常紧张':'有所戒备'}。`};save();renderGame()}
function profileLine(n,ns){let m={lin:'“年轻人，怀疑是理性的开端，但别让它成为结论。”',su:'“如果没有具体问题，请不要浪费彼此的时间。”',chen:'“唉，出了这种事……我这当列车员的脸往哪搁。”',jie:'“别这么盯着我。一个人失踪而已，也许他自己跑了呢？”',wang:'“那滩液体未必是血。没有化验，我不会下结论。”',yu:'“我……我真的没看到什么。”',zhao:'“周明？那小子我看他就不顺眼。但我犯不上动他。”',mute:'（他抬眼看了你一瞬，又重新缩进军大衣里。）'};return m[n.id]}
function moveTo(c){let d=Math.abs(c-S.currentCar);if(d===0)return;if(d>1){if(!confirm('跨越非相邻车厢将消耗 1 个回合。继续？'))return;S.currentCar=c;S.selected=null;S.scene={speaker:carriages[c-1].name,text:carriages[c-1].desc,obs:'你穿过几节车厢。有人注意到了你的行踪。'};endTurn('长距离移动');}else{S.currentCar=c;S.selected=null;S.scene={speaker:carriages[c-1].name,text:carriages[c-1].desc,obs:'相邻移动不消耗回合。'};save();renderGame()}}
function overlay(html){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="overlay" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`)}function closeModal(){$('#overlay')?.remove()}function chosenButton(e){document.querySelectorAll('.option').forEach(x=>x.classList.remove('chosen'));e.currentTarget.classList.add('chosen');e.currentTarget.querySelector('input')?.click()}
function askModal(){let n=npc(S.selected);overlay(`<h2>询问 ${n.name}</h2><p class="modal-sub">你的措辞会改变信任与压力。</p><div class="options">${['案发时你在哪里？','你认识周明吗？','你为什么坐这趟车？','你有没有听到异常？','你觉得谁最可疑？','你在隐瞒什么？'].map(q=>`<button class="option" onclick="document.querySelector('#question').value='${q}'">${q}</button>`).join('')}</div><label class="field">或自由提问<textarea id="question" placeholder="输入你的问题……"></textarea></label><div class="modal-actions"><button class="btn" onclick="closeModal()">取消</button><button class="btn primary" onclick="doAsk()">提问</button></div>`) }
async function doAsk(){let q=$('#question').value.trim();if(!q)return toast('请先输入问题');let n=npc(S.selected);closeModal();S.scene={speaker:n.name,text:'……',obs:`${n.name}正在斟酌如何回答。`};renderGame();let ans=await answer(n,q);state(n.id).interactions++;let hostile=/凶手|杀|撒谎|隐瞒|动机|证据/.test(q);state(n.id).trust=clamp(state(n.id).trust+(hostile?-.08:.06));state(n.id).stress=clamp(state(n.id).stress+(hostile?.12:-.025));state(n.id).asked.push(q);S.scene={speaker:n.name,text:ans.text,obs:ans.obs};S.notes.push({round:S.round,text:`你问${n.name}：“${q}” ${ans.note}`});endTurn(`你询问了${n.name}`)}
async function answer(n,q){if(C.apiBase&&C.apiKey){try{return await aiAnswer(n,q)}catch(e){toast('列车进入隧道，已切换本地叙事')}}let ns=state(n.id),cul=S.culprit===n.id,knows=ns.trust>.5||ns.stress>.7;let a='',obs='';if(n.id==='mute'){S.muteTalks++;if(S.muteTalks<2)a='（他低着头，只朝餐车方向指了指。）';else if(S.muteTalks<3)a='“……有人。出去过。”';else{a=`“零点以后……有人从餐车拖着东西，往行李车走。” 他停了很久，${cul?'“那个人……像是我。可我记不清了。”':`“是${npc(S.culprit).name}。”`}`;if(!cul)addWitness();}obs='他的手指在发抖，但动作很确定。';return{text:a,obs,note:'他提供了片段化的目击信息。'}}
if(/哪里|案发时|不在场/.test(q)){a=cul?pick(['“我一直在自己的位置，没有离开。有人能证明。”','“大约十二点？我在休息。时间我记不清了。”']):`“接近午夜时，我在${carriages[ns.car-1].name}。${ns.interactions?'我之前已经说过了。':''}”`;obs=cul?'回答很快，像是已经排练过。':'他先回忆了一下钟表的位置。'}
else if(/认识|关系|周明/.test(q)){if(n.id==='yu'&&knows){a='“他是我哥哥。” 她终于抬起头，“他失联了三天，我是追着信用卡记录上车的。”';ns.revealed=true}else if(cul)a='“见过，但谈不上认识。他主动找过我，仅此而已。”';else a=pick(['“只是在车上见过。他看起来心事很重。”','“我们说过几句话，但我不了解他。”']);obs=ns.revealed?'这句话几乎用尽了她的力气。':'提到周明时，他的视线短暂移开。'}
else if(/为什么|坐这趟车|目的/.test(q)){a=`“只是去南方办点私事。”`;if(knows&&!cul)a+=` 他沉默片刻，“不过，私事和这桩案子无关。”`;obs='“私事”两个字被刻意加重。'}
else if(/听到|看到|异常|声音/.test(q)){a=cul?'“没有。车轮声太响了，我什么也没听到。”':pick(['“零点前后，我听见餐车方向有短促的争执声。”','“有人经过走廊，但灯太暗，我没看清。”','“我听见行李车那边像有重物落地。”']);obs=cul?'他的手在回答时悄悄攥紧。':'这段记忆似乎让他不安。'}
else if(/可疑|怀疑|凶手/.test(q)){let target=cul?pick(NPCS.filter(x=>x.id!==n.id&&x.id!=='yu')):npc(pick(['jie','zhao','su']));a=`“${target.name}不太对劲。你应该问问${target.id==='su'?'那个银色箱子':'他的真实行程'}。”`;obs=cul?'他在试图给你的怀疑指明方向。':'这更像直觉，而不是证据。'}
else if(/隐瞒|秘密|撒谎/.test(q)){if(knows){a=`“好吧。我确实瞒了一件事：${n.secret}但那不代表我伤害了周明。”`;ns.revealed=true}else{a='“每个人都有不愿被陌生人翻看的过去。这不是犯罪。”';S.lies++}obs=knows?'防线终于出现裂缝。':'他的防御姿态更明显了。'}
else{a=cul?'“你的问题和周明的失踪有什么关系？”':`“我只能告诉你我确定的事。猜测会害了人。”`;obs=`${n.name}保持着${n.style}的语气。`}
return{text:a,obs,note:cul?'他的回答可能需要交叉验证。':'这段证词已记入笔记。'}}
async function aiAnswer(n,q){let base=C.apiBase.replace(/\/$/,'');let prompt=`你在中文悬疑游戏《午夜列车》中扮演${n.name}。性格：${n.style}。秘密：${n.secret}。你${S.culprit===n.id?'就是凶手，必须合理隐瞒':'不是凶手'}。当前信任${state(n.id).trust.toFixed(2)}，压力${state(n.id).stress.toFixed(2)}。真实凶手是${npc(S.culprit).name}，但除非你是目击者不要直接知道。玩家问：“${q}”。请返回JSON：{"text":"80字内角色回答","obs":"20字内动作观察","note":"20字内笔记摘要"}。只输出JSON。`;let r=await fetch(base+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+C.apiKey},body:JSON.stringify({model:C.model||'gpt-4o-mini',messages:[{role:'system',content:'严格扮演角色，保持案件一致性，输出合法JSON。'},{role:'user',content:prompt}],temperature:.65})});if(!r.ok)throw Error(r.status);let j=await r.json(),t=j.choices[0].message.content.replace(/```json|```/g,'').trim();return JSON.parse(t)}
function addWitness(){if(S.collected.includes('witness'))return;S.clues.push({id:'witness',name:'哑叔的完整目击',desc:`哑叔确认零点后看见${npc(S.culprit).name}从餐车向行李车拖动重物。`,key:true,found:true});S.collected.push('witness')}
function searchModal(){let c=carriages[S.currentCar-1];overlay(`<h2>搜查 · ${c.name}</h2><p class="modal-sub">选择一个区域。本行动将消耗 1 个回合。</p><div class="options">${c.areas.map((a,i)=>`<button class="option" onclick="doSearch(${i})"><b>${esc(a)}</b><br><small style="color:var(--muted)">${S.searched[S.currentCar+'-'+i]?'已经搜查过':'尚未搜查'}</small></button>`).join('')}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">取消</button></div>`) }
function doSearch(i){closeModal();let key=S.currentCar+'-'+i,count=S.searched[key]||0;S.searched[key]=count+1;let found=S.clues.find(c=>!c.found&&c.car===S.currentCar&&c.areaIndex===i);if(!found&&count===0)found=S.clues.find(c=>!c.found&&c.car===S.currentCar);if(found&&(count===0||chance(.2))){found.found=true;S.collected.push(found.id);S.scene={speaker:'发现线索 · '+found.name,text:found.desc,obs:found.key?'这可能是证据链的一部分。':'它暴露了某人的秘密，却未必指向本案。'};S.notes.push({round:S.round,text:`在${carriages[S.currentCar-1].name}${carriages[S.currentCar-1].areas[i]}发现「${found.name}」。`});state(S.culprit).stress=clamp(state(S.culprit).stress+.08)}else{S.scene={speaker:'搜查无果',text:count>1?'你再次检查了每一道缝隙。这里已经不会再告诉你更多。':pick(['只有积尘、皱纸和一枚过期车票。','你闻到潮湿金属的味道，却没找到可用的东西。','一道新鲜擦痕延伸到阴影里，随后消失。']),obs:'并非每次行动都会得到答案。'}}endTurn(`你搜查了${carriages[S.currentCar-1].areas[i]}`)}
function eavesdrop(){let here=NPCS.filter(n=>state(n.id).car===S.currentCar),pair=here.slice(0,2),p=.7-(pair.some(n=>state(n.id).suspicion>.5)?.2:0);if(chance(p)){let c=S.culprit,mentions=pair.some(n=>n.id===c);S.scene={speaker:`偷听 · ${pair[0].name} × ${pair[1].name}`,text:mentions?`“玩家已经找到了一些东西。”\n“那你紧张什么？”\n“我没有紧张。倒是${npc(pick(['jie','zhao','wang'])).name}，你不觉得可疑吗？”`:`“每个人都在撒谎。”\n“撒谎不等于杀人。周明失踪前，我看见有人往${S.culprit==='mute'?'行李车':'餐车'}去了。”`,obs:'他们没有发现你。对话中的停顿也许比内容更重要。'};S.notes.push({round:S.round,text:`偷听到${pair[0].name}与${pair[1].name}的私下谈话。`})}else{pair.forEach(n=>{state(n.id).trust=clamp(state(n.id).trust-.2);state(n.id).suspicion=clamp(state(n.id).suspicion+.2)});S.scene={speaker:'偷听失败',text:'门忽然被拉开。两个人同时看向藏在阴影里的你。','obs':'他们不会再轻易在你面前交谈。'}}endTurn('你尝试偷听谈话')}
function evidenceModal(){let n=npc(S.selected);overlay(`<h2>向${n.name}出示证据</h2><p class="modal-sub">对方的第一反应往往比回答更诚实。</p><div class="options">${S.collected.map(id=>{let c=S.clues.find(x=>x.id===id);return`<button class="option" onclick="showEvidence('${id}')">${c.key?'🔸':'🔹'} <b>${esc(c.name)}</b><br><small style="color:var(--muted)">${esc(c.desc)}</small></button>`}).join('')}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">取消</button></div>`) }
function showEvidence(id){closeModal();let c=S.clues.find(x=>x.id===id),n=npc(S.selected),related=S.culprit===n.id&&c.key||c.owner===n.id;state(n.id).stress=clamp(state(n.id).stress+(related?.22:.04));state(n.id).suspicion=clamp(state(n.id).suspicion+.12);let text,obs;if(related){text=S.culprit===n.id?'“这能证明什么？任何人都可能把它放在那里。”':'“你没有权利翻我的东西……这和周明的失踪无关。”';obs=S.culprit===n.id?'否认来得太快。他甚至没有先看清证物。':'他的震惊指向另一个秘密，而不一定是谋杀。'}else{text= n.id==='wang'?`“从保存状态看，它出现的时间应该不超过两小时。”`:'“我没见过这个。你应该问问它是在哪里发现的。”';obs='反应更像困惑，而非恐惧。'}S.scene={speaker:`${n.name} · 面对「${c.name}」`,text,obs};S.notes.push({round:S.round,text:`向${n.name}出示「${c.name}」：${obs}`});endTurn(`你向${n.name}出示了证据`)}
function follow(){let n=npc(S.selected),success=chance(.6+(S.identity==='journalist'?.1:0)-state(n.id).suspicion*.25);if(success){let dest=S.culprit===n.id?4:Math.max(1,Math.min(4,state(n.id).car+(chance(.5)?1:-1)));state(n.id).car=dest;S.scene={speaker:'跟踪成功',text:S.culprit===n.id?`${n.name}绕开人群走进行李车，在一堆箱子前停下。他确认某样东西仍藏在那里，随后迅速离开。`:`${n.name}去了${carriages[dest-1].name}，和那里的人低声交谈。他似乎只是在寻求一个不被打扰的角落。`,obs:'你没有被发现。'};S.notes.push({round:S.round,text:`跟踪${n.name}到${carriages[dest-1].name}。`})}else{state(n.id).trust=clamp(state(n.id).trust-.25);state(n.id).suspicion=clamp(state(n.id).suspicion+.25);S.scene={speaker:'跟踪暴露',text:`${n.name}突然停步，回头看向你：“你到底想干什么？”`,obs:'你失去了他的信任。'}}endTurn(`你跟踪了${n.name}`)}
function npcActions(){let events=[];NPCS.forEach(n=>{let ns=state(n.id);if(n.id===S.culprit&&S.collected.filter(id=>S.clues.find(c=>c.id===id)?.key).length>=2){ns.stress=clamp(ns.stress+.06);if(chance(.32)){ns.car=4;events.push(`${n.name}避开人群，悄悄去了行李车。`)}}else if(chance(.13)){let old=ns.car,dir=chance(.5)?1:-1;ns.car=Math.max(1,Math.min(4,old+dir));if(old!==ns.car&&(old===S.currentCar||ns.car===S.currentCar))events.push(`${n.name}${ns.car===S.currentCar?'走进了你所在的车厢':'离开后消失在连接门后'}。`)}});if(!events.length)events.push(pick(['远处传来一阵压低的争执声。','有人在隔壁车厢来回踱步。','所有人都异常安静，像在等待什么。','餐车的灯又闪了几下。']));if(chance(.2))events.push(pick(['列车突然晃了一下，杯子跌落在地。','广播发出一段无法辨认的杂音。','暴雨敲打车窗，所有人短暂地看向窗外。']));return events.slice(0,3)}
function endTurn(action){S.events.push(action);let ev=npcActions(),atm=atmosphere[Math.min(S.round-1,9)];save();if(S.round>=10){S.round=10;save();eventModal(ev,atm,true);return}S.round++;save();eventModal(ev,atm,false)}
function eventModal(ev,atm,forced){overlay(`<div class="eyebrow">回合记录</div><h2>${forced?'终点站即将抵达':`第 ${S.round-1} 回合结束`}</h2><p class="modal-sub">列车在黑暗中继续前行。你注意到一些变化——</p><div class="event-list">${ev.map(e=>`<div class="event">${esc(e)}</div>`).join('')}</div><p class="atmosphere">“${esc(atm)}”</p><div class="modal-actions">${forced?`<button class="btn danger" onclick="closeModal();accuseModal(true)">做出最终指认</button>`:`<button class="btn primary" onclick="closeModal();renderGame()">继续调查 · 剩余 ${11-S.round} 回合</button>`}</div>`) }
function clueDetail(id){let c=S.clues.find(x=>x.id===id);overlay(`<div class="eyebrow">EVIDENCE / ${c.key?'关键物证':'关联秘密'}</div><h2>${esc(c.name)}</h2><p class="rules">${esc(c.desc)}</p><div class="modal-actions"><button class="btn primary" onclick="closeModal()">收起</button></div>`) }
function accuseModal(forced=false){overlay(`<h2>⚠ 做出指认</h2><p class="modal-sub">这是唯一的机会。${forced?'列车即将到站，你不能再拖延。':''}</p><div class="options">${NPCS.map(n=>`<label class="option" onclick="chosenButton(event)"><input type="radio" name="acc" value="${n.id}"> ${n.icon} ${n.name} <small style="color:var(--muted)">· ${n.job}</small></label>`).join('')}</div><label class="field">你的推理（可选）<textarea id="reason" placeholder="动机、手法与证据链……"></textarea></label><div class="modal-actions">${!forced?'<button class="btn" onclick="closeModal()">再想想</button>':''}<button class="btn danger" onclick="confirmAccuse()">确认指认</button></div>`) }
function confirmAccuse(){let r=document.querySelector('input[name=acc]:checked');if(!r)return toast('请选择一名嫌疑人');if(!confirm(`确认指认 ${npc(r.value).name}？此决定无法撤回。`))return;S.accused=r.value;S.reason=$('#reason').value.trim();S.ended=true;S.active=false;S.screen='result';let st=load(STATS)||{played:0,won:0,best:'F',fastest:null};st.played++;if(r.value===S.culprit){st.won++;st.fastest=!st.fastest?S.round:Math.min(st.fastest,S.round)}localStorage.setItem(STATS,JSON.stringify(st));save();closeModal();resultPage(r.value)}
function resultPage(accused){let win=accused===S.culprit,cul=npc(S.culprit),keys=S.collected.filter(id=>S.clues.find(c=>c.id===id)?.key).length,grade=win?(S.round<=6&&keys>=6?'S':S.round<=8&&keys>=5?'A':keys>=3?'B':'C'):'F';let timeline=[['23:15',`周明与${cul.name}发生争执。`],['23:45',`${cul.name}以私事为由离开原车厢。`],['00:00',`${cul.name}抵达餐车，与周明对质。`],['00:15','暗红色染料被打翻，周明失去反抗能力。'],['00:20',`${cul.name}将周明与关键物品转移至行李车夹层。`],['01:13','小雨发现空座位，尖叫惊动全车。']];app.innerHTML=`<section class="result"><div class="result-card"><div class="eyebrow">CASE CLOSED / K1024</div><h1 class="verdict ${win?'win':'lose'}">${win?'你找到了真相。':'真相被留在黑暗中。'}</h1><div class="culprit-reveal">真正的凶手：<b style="color:${win?'var(--amber)':'#d96a6f'}">${cul.icon} ${cul.name}</b><br><small style="color:var(--muted);font-family:var(--sans)">动机：${esc(S.motive)}</small></div><h3>案发时间线</h3><div class="timeline">${timeline.map(x=>`<div><time>${x[0]}</time><span>${esc(x[1])}</span></div>`).join('')}</div><h3>调查结算</h3><div class="score-row"><div class="score"><strong>${grade}</strong>调查评级</div><div class="score"><strong>${S.round}/10</strong>使用回合</div><div class="score"><strong>${S.collected.length}/8</strong>发现线索</div><div class="score"><strong>${S.lies}</strong>可疑谎言</div></div>${!win?`<p class="rules">你指认了 <b>${npc(accused).name}</b>。你错过的关键是：${S.clues.filter(c=>c.key&&!c.found).slice(0,2).map(c=>c.name).join('、')||'证词之间的矛盾'}。</p>`:''}<div class="modal-actions" style="justify-content:flex-start"><button class="btn primary" onclick="identityPage()">再来一局</button><button class="btn" onclick="shareResult('${grade}',${win})">分享结果</button><button class="btn ghost" onclick="landing()">返回首页</button></div></div></section>`}
function shareResult(g,w){let t=`《午夜列车》调查完成｜${w?'成功找到真凶':'真相仍在黑暗中'}｜评级 ${g}｜${S.round} 回合，发现 ${S.collected.length} 条线索。`;navigator.clipboard?.writeText(t).then(()=>toast('战报已复制')).catch(()=>prompt('复制战报',t))}
function rules(inGame=false){overlay(`<div class="eyebrow">INVESTIGATION MANUAL</div><h2>调查规则</h2><div class="rules"><h3>十个回合，一次机会</h3><p>每回合可执行一个主行动：询问、偷听、搜查、出示证据或跟踪。相邻车厢移动免费，跨越多节车厢消耗一回合。</p><h3>不要把秘密当作谋杀</h3><p>八名乘客都在撒谎，但他们隐瞒的事未必与周明有关。交叉验证证词、物证与行为。</p><h3>活着的嫌疑人</h3><p>每回合后 NPC 会移动、交谈和隐藏证据。信任让人开口，压力则可能让谎言出现裂缝。</p><h3>本地存档</h3><p>游戏自动保存在浏览器中。刷新或离开后可继续。</p></div><div class="modal-actions"><button class="btn primary" onclick="closeModal()">明白了</button></div>`) }
function settings(inGame=false){let st=load(STATS)||{played:0,won:0};overlay(`<div class="eyebrow">SYSTEM / CONFIGURATION</div><h2>设置</h2><p class="modal-sub">无需 AI 配置也可完整游玩。填写兼容 OpenAI 的接口后，自由问答将由模型生成。</p><label class="field">API 地址<input id="apiBase" value="${esc(C.apiBase)}" placeholder="https://api.openai.com/v1"></label><label class="field">API 密钥<input id="apiKey" type="password" value="${esc(C.apiKey)}" placeholder="仅保存在此浏览器 localStorage"></label><label class="field">模型名称<input id="model" value="${esc(C.model)}" placeholder="gpt-4o-mini"></label><div class="settings-grid"><label class="field">文字速度<select id="speed"><option value="slow">慢</option><option value="normal">正常</option><option value="fast">快</option><option value="instant">即时</option></select></label><div class="switch"><span>环境音效（预留）</span><input id="sound" type="checkbox" ${C.sound?'checked':''}></div></div><p class="modal-sub">已调查 ${st.played||0} 局 · 成功 ${st.won||0} 局 · 胜率 ${st.played?Math.round(st.won/st.played*100):0}%</p><div class="modal-actions"><button class="btn danger" onclick="clearData()">清除数据</button><button class="btn" onclick="closeModal()">取消</button><button class="btn primary" onclick="saveSettings()">保存</button></div>`);$('#speed').value=C.speed}
function saveSettings(){C.apiBase=$('#apiBase').value.trim();C.apiKey=$('#apiKey').value.trim();C.model=$('#model').value.trim();C.speed=$('#speed').value;C.sound=$('#sound').checked;cfgSave();closeModal();toast('设置已保存')}
function clearData(){if(confirm('清除全部存档、设置与统计？')){localStorage.removeItem(STORE);localStorage.removeItem(CFG);localStorage.removeItem(STATS);C={sound:true,speed:'normal',apiBase:'',apiKey:'',model:''};closeModal();landing()}}
landing();